apiVersion: v1
kind: Service
metadata:
  name: travelpack-service
  namespace: travelpack
spec:
  selector:
    app: travelpack
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32453
  type: NodePort
